---
  :concurrency: 5
  :max_retries: 3
  :schedule:
    CheckRadio1:
      cron: '*/3 * * * *' # every 3 minutes
      queue: default
      enabled: true
    CheckRadio2:
      cron: '*/3 * * * *'
      queue: default
      enabled: true
    CheckRadio3:
      cron: '*/3 * * * *'
      queue: default
      enabled: true
    CheckRadio4:
      cron: '*/3 * * * *'
      queue: default
      enabled: true
    CheckRadio5:
      cron: '*/3 * * * *'
      queue: default
      enabled: true
    CheckRadio10:
      cron: '*/3 * * * *'
      queue: default
      enabled: true
    CheckRadio538:
      cron: '*/3 * * * *'
      queue: default
      enabled: true
    CheckRadioVeronica:
      cron: '*/3 * * * *'
      queue: default
      enabled: true
    CheckSkyRadio:
      cron: '*/3 * * * *'
      queue: default
      enabled: true
    CheckQmusic:
      cron: '*/3 * * * *'
      queue: default
      enabled: true
    CheckGrootNieuwsRadio:
      cron: '*/3 * * * *'
      queue: default
      enabled: true
    CheckSublimeFm:
      cron: '*/3 * * * *'
      queue: default
      enabled: true
    SendStatusEmail:
      cron: '0 2 * * *' # at 2am
      queue: default
      enabled: true
  :sidekiq_default_hooks: true
  :sidekiq_pid: File.join(shared_path, 'tmp', 'pids', 'sidekiq.pid')
  :sidekiq_env: fetch(:rack_env, fetch(:rails_env, fetch(:stage)))
  :sidekiq_log: File.join(shared_path, 'log', 'sidekiq.log')
  :sidekiq_options: nil
  :sidekiq_require: nil
  :sidekiq_tag: nil
  :sidekiq_config: nil
  :sidekiq_queue: nil
  :sidekiq_timeout: 10
  :sidekiq_role: :app
  :sidekiq_processes: 1
  :sidekiq_concurrency: nil